<?php
return [
'cnpj' => '',
'name' => '',
'banco' => '',
'agencia' => '',
'conta' => '',
'cep' => '',
'logradouro' => '',
'numero' => '',
'complemento' => '',
'bairro' => '',
'municipio' => '',
'uf' => '',
'company_phone' => '',
'email' => '',
'valor_locador' => '',
'valor_percent' => '',
'valor_locacao' => '',
'cnpj_locador' => '',
'name_locador' => '',
'cep_locador' => '',
'logradouro_locador' => '',
'numero_locador' => '',
'complemento_locador' => '',
'bairro_locador' => '',
'municipio_locador' => '',
'uf_locador' => '',
'company_phone_locador' => '',
'email_locador' => '',
]
?>
